name: Publish to PyPI


on:
  push:
    tags:
      # Trigger only on version tags
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      -
        name: Checkout repository
        uses: actions/checkout@v6

      -
        name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      -
        name: Install Poetry
        run: pip install poetry

      -
        name: Install dependencies
        run: poetry install

      -
        name: Build and Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry build
          poetry publish --username __token__ --password $POETRY_PYPI_TOKEN_PYPI
